# see https://github.com/ahmadnassri/action-dependabot-auto-merge
name: Auto Merge Dependabot

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor  # patch|minor|major
          github-token: ${{ secrets.TOKEN_AUTOMERGE }}
